version: '3.8'

services:
  nodered:
    restart: always
    ports:
      - "1880:1880"
    depends_on:
      - backend
    volumes:
      - ./frontend_NodeRED:/data
    environment:
      - TZ=Asia/Tokyo
    build: ./frontend_NodeRED
