version: '3.8'

services:
  nodered:
    restart: always
    ports:
      - "1880:1880"
    depends_on:
      - backend
    volumes:
      - ./frontend_NodeRED:/data
    environment:
      - TZ=Asia/Tokyo
    build: ./frontend_NodeRED

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - nodered
